create table trainer (
    id            bigint generated by default as identity primary key,
    username      varchar(20)  not null unique,
    password_hash varchar(100) not null,
    created_at    timestamptz  not null default now()
);

create table move (
    id       bigint primary key,
    name     varchar(40) not null unique,
    element  varchar(10) not null check (element in ('AGUA', 'ROCHA', 'FOGO', 'GELO', 'GRAMA', 'RAIO')),
    power    int not null check (power >= 0),
    accuracy int not null check (accuracy between 1 and 100),
    max_pp   int not null check (max_pp > 0)
);

create table species (
    id         bigint primary key,
    name       varchar(40) not null unique,
    element    varchar(10) not null check (element in ('AGUA', 'ROCHA', 'FOGO', 'GELO', 'GRAMA', 'RAIO')),
    base_hp    int not null check (base_hp > 0),
    base_atk   int not null check (base_atk > 0),
    base_def   int not null check (base_def > 0),
    base_spd   int not null check (base_spd > 0)
);

-- Golpes de cada especie, na ordem em que aparecem no menu de batalha.
create table species_move (
    species_id bigint not null references species (id),
    slot       int    not null check (slot >= 0),
    move_id    bigint not null references move (id),
    primary key (species_id, slot)
);

-- O nivel e derivado do XP (ExperienceCurve), por isso nao e armazenado.
create table monster (
    id         bigint generated by default as identity primary key,
    trainer_id bigint      not null references trainer (id) on delete cascade,
    species_id bigint      not null references species (id),
    nickname   varchar(40) not null,
    xp         int         not null check (xp >= 0),
    current_hp int         not null check (current_hp >= 0),
    team_slot  int check (team_slot between 0 and 5),
    -- Adiado para permitir trocar slots dentro da mesma transacao.
    constraint monster_team_slot_uk unique (trainer_id, team_slot) deferrable initially deferred
);
create index monster_trainer_idx on monster (trainer_id);

create table monster_move_pp (
    monster_id bigint not null references monster (id) on delete cascade,
    slot       int    not null check (slot >= 0),
    pp_left    int    not null check (pp_left >= 0),
    primary key (monster_id, slot)
);

create table battle (
    id         bigint generated by default as identity primary key,
    trainer_id bigint      not null references trainer (id) on delete cascade,
    status     varchar(20) not null,
    state      jsonb       not null,
    version    int         not null default 0,
    created_at timestamptz not null default now()
);
-- No maximo uma batalha em andamento por treinador.
create unique index battle_one_active_per_trainer on battle (trainer_id) where status = 'AWAITING_ACTION';
